### ISSUE TITLE
Suggested fix for specan slow processing

### ISSUE THREAD

**Issue by primaryobjects** [maRce10/warbleR#11]
Great library. I've been using it to do some basic sound analysis. I'm using the method specan() and it runs extremely slowly, sometimes taking over an hour to process 30 wav files. This is due to the call fpeaks(). I've commented out this [line](https://github.com/maRce10/warbleR/blob/master/R/specan.R#L165) and it runs much faster (about 10s).

It might be nice to add a parameter to the method to either optionally disable this measurement or to provide a vector of indices for which measurements to return.

```r
specan <- function(X, bp = c(0,22), wl = 512, threshold = 15, features = c(1:22), parallel = 1)
```

The above signature is just an example, adding ```features = c(1:22)``` to indicate to use all 22 measurements. So to remove peakf, you would pass ```features = c(1:13, 15:22)```. Or maybe just a boolean. Just a suggestion. Thanks!

**Comment by maRce10** [comment]
Great suggestion, I will include something to let users choose which parameters they want.

Thanks!

**Comment by maRce10** [comment]
FYI, we have fixed this by adding a logical argument called "fast". If T (default) peakf is not computed.

thanks again
