### ISSUE TITLE
Installing with RStudio

### ISSUE THREAD

**Issue by madelynore** [maRce10/warbleR#12]
Hello,

I tried to install warbleR to RStudio and received the following error messages: 

```
Warning: package 'maps' was built under R version 3.3.3
Warning: package 'seewave' was built under R version 3.3.3
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'signal'
Error : package 'seewave' could not be loaded
ERROR: lazy loading failed for package 'warbleR'
```

I tried to install 'seewave' separately, but this didn't seem to solve the problem. Do you have any suggestions? 

Thanks
Madelyn

**Comment by maRce10** [comment]
Hi!

it seems that you need to update R to version 3.3.3.  If you keep having problems there are some known issues when installing seewave. Check here (http://rug.mnhn.fr/seewave/inst.html) for some tips.

Cheers

Marcelo
