### ISSUE TITLE
bug in xcorr.R?

### ISSUE THREAD

**Issue by gauravsk** [maRce10/warbleR#14]
Hi,

I am writing to report a potential bug in the `xcorr()` function. We were using it to build a cross-correlation matrix for a dataset of North American passerines that looks like this:

```
head(sound_times)

               sound.files      start      end selec
1   Spizella_pallida_a.wav 0.14862887 1.085007     1
2   Spizella_pallida_b.wav 0.73852067 2.153167     1
3 Spizella_passerina_a.wav 0.15001337 1.666764     1
4 Spizella_passerina_b.wav 1.10819695 3.254702     1
5   Spizella_pusilla_a.wav 0.05395893 1.615225     1
6   Spizella_pusilla_b.wav 0.07101049 1.369515     1
```

We ran the following command:
```
xcorr(X=sound_times,wl=512,frange = c(0,12),ovlp=90,dens=0.9,wn="hanning",cor.method="pearson",cor.mat=FALSE)
```

and got the following error: 

```
creating templates:
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 10s
running cross-correlation:
   |++++                                              | 8 % ~34s          
Error in if (end > a$samples/a$sample.rate) end <- a$samples/a$sample.rate -  : 
  missing value where TRUE/FALSE needed
```

The error seems to originate in lines 274-280 of the `xcorr()` function:

```
274  margin <-(max(with(X, end[j:nrow(X)] - start[j:nrow(X)])))/2
275   start <-X$start[j] - margin
276   if(start < 0) {
277     end <-X$end[j] + margin -start[j]
278     start <- 0} else
279   end <-X$end[j] + margin
280 if(end > a$samples/a$sample.rate) end <- a$samples/a$sample.rate - 0.001
```
It looks like the variable `start` is set to a single number on line 275; yet it is subsetted by `j` (which takes values of `1:nrow(X)-1`) on line 277. 

We were able to get the function to work by redefining it without the `j` subset (i.e. line 277 was changed as follows):

```
277     end <-X$end[j] + margin -start
```

and got results as we expected. 

Can you check whether this is the correct fix or whether we were lucky in getting back expected results?

Thanks for your work on this helpful package!

**Comment by gauravsk** [comment]
@madcowen

**Comment by maRce10** [comment]
Hi Gaurav

thanks for reporting this bug. I have included your solution in the code now. 

best
