### ISSUE TITLE
Using warbleR to download 

### ISSUE THREAD

**Issue by dododave** [maRce10/warbleR#15]
Hi Macelo,

Is it possible to use warbleR to download an entire set of recordings I have made in xeno-canto? I have been able to this using your handy package for all the recordings of a certain genus or other XC 
descriptors such as location or country, but what about sets?

Thanks,
David Bradley

**Comment by maRce10** [comment]
Hi David

sorry for the late response. I am not sure what you mean with set of recordings, but note that you can use the ["XC advance query"](http://www.xeno-canto.org/help/search) to do more specific queries. For instance, this will search all of my recordings:

mas.recs <- querxc(qword = 'rec:"Marcelo Araya-Salas"')

these are other examples (which are included in the function documentation):

# genus orthonyx from Tari Papua
orth.pap <- querxc(qword = 'gen:orthonyx cnt:papua loc:tari', download = FALSE)
 
# use quotes for queries with more than 1 word (e.g. Costa Rica),note that the 
# single quotes are used for the whole 'qword' and double quotes for the 2-word term inside
#Phaeochroa genus in Costa Rica 
phae.cr <- querxc(qword = 'gen:phaeochroa cnt:"costa rica"', download = FALSE)

# several terms can be searched for in the same field
# search for all female songs in sound type
femsong <- querxc(qword = 'type:song type:female', download = FALSE)
