### ISSUE TITLE
Error with catalog()

### ISSUE THREAD

**Issue by madelynore** [maRce10/warbleR#18]
I have been trying to create a catalog from my sound files. It works with the sample sound files, but not with my own. I have a data frame with all of the correct column names and (presumably the right classes - sound.files (character), selec (integer), start (numeric), end (numeric) ). I have tried using the selection_table() function to turn my data frame into a selection table. But I get the same error every time:

> Error in dimnames(x) <- dn : 
>   invalid type (closure) for 'dimnames' (must be a vector)

This is my code: 

```
#slc is a file with selection info (sound.files, selec, start, end)
l_song <- selection_table(slc[1:10,])

catalog(l_song, wl = 512, it = "jpeg", res = 100, ovlp = 50, nrow= 3, ncol = 3, fast.spec = TRUE)
```

**Comment by maRce10** [comment]
Can you create an extended selection table and share it as an RDS object? 

You can do it like this:

```
l_song <- selection_table(slc[1:10,], extended = TRUE, confirm.extended = FALSE)
 
saveRDS(l_song, "ext.sel.tab.RDS")
```

and attach the RDS file to your comment

thanks

**Comment by madelynore** [comment]
It was an issue with the version, Thanks
