### ISSUE TITLE
Decimal error in Vignette causes crash

### ISSUE THREAD

**Issue by cooperii** [maRce10/warbleR#20]
Minor error in the WarbleR vignette "warbleR_workflow_01.html". In the mp32wav conversion step, samp.rate should be in kHz.

> # here we are downsampling the original sampling rate of 44.1 kHz to speed up downstream analyses in the vignette series
> mp32wav(samp.rate = 22050)

**Comment by maRce10** [comment]
Thanks for the heads up! I just fixed it and pulled the update.
