### ISSUE TITLE
numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by paddygoat** [maRce10/warbleR#21]
library(warbleR)
df1 = quer_xc(qword ='Catharus bicknelli type:call cnt:"United States"', download = FALSE)
| | 0 % ~calculating Error in rbind(deparse.level, ...) :
numbers of columns of arguments do not match

**Comment by maRce10** [comment]
Thanks.

Xeno-Canto updated the API adding new fields. That created the problem. But it's already fixed. Install warbleR again from github.
