### ISSUE TITLE
Error in rbind

### ISSUE THREAD

**Issue by mun3im** [maRce10/warbleR#22]
Cannot complete querxc() function call.

querxc("q:A", download=FALSE)
   |                                                  | 0 % ~calculating  Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

**Comment by maRce10** [comment]
Thanks. 

Xeno-Canto updated the API adding new fields. That created the problem. But it's already fixed.  Install warbleR again from github.

**Comment by mun3im** [comment]
Still doesn't work. The following was run on macOS.

> devtools::install_github("maRce10/warbleR")
Skipping install of 'warbleR' from a github remote, the SHA1 (b8043a80) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github("maRce10/warbleR",force=TRUE)
Downloading GitHub repo maRce10/warbleR@master
✔  checking for file ‘/private/var/folders/d_/1db4s9h155l_9d05pbnq28l00000gn/T/RtmplLnDql/remotes3256cf79d6f/maRce10-warbleR-b8043a8/DESCRIPTION’ ...
─  building ‘warbleR_1.1.18.tar.gz’ation ...
   
* installing *source* package ‘warbleR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (warbleR)
 
> library(warbleR)
> my <- querxc("cnt:malaysia")
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 53s
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
>

**Comment by maRce10** [comment]
I just tried in Linux and worked fine:

`my <- querxc("cnt:malaysia")
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 09s
7965 recordings found!`

try installing it again from github

Marcelo

**Comment by mun3im** [comment]
All right!
It works in Linux.
It means I have to work in the lab and not bring any work home!

Thanks!!

**Comment by maRce10** [comment]
hahaha exactly! 

cheers
