### ISSUE TITLE
querxc would not work

### ISSUE THREAD

**Issue by StormPetrel5** [maRce10/warbleR#23]
Hi, 
Sorry if this is too basic... 
I'm trying to select (to then download) some recordings from XC by using the querxc function:

> PHY <- querxc(qword = "Phylloscopus", download = FALSE) 

But I only obtain the following error:

>  Error in rbind(deparse.level, ...) : 
>   numbers of columns of arguments do not match

I understand this error occurs when I'm trying to sort of import something that has n columns into something that has x columns, but how can this be the case? I've also tried to left my variable undefined and using the print function instead, but it doesn't work either.
I see this is not a very active forum, but maybe somebody would google a similar problem at some point... 
Notice this is the very first line of code so I'm stack right at the beginning...

**Comment by maRce10** [comment]
Thanks.

Xeno-Canto updated the API adding new fields. That created the problem. But it's already fixed. Install warbleR again from github.

**Comment by StormPetrel5** [comment]
Hi Marcelo,

Thanks for your quick reply. I've installed warbleR again from github:

> install.packages("devtools")
> devtools::install_github("maRce10/warbleR")

But I still get the same error message...

**Comment by maRce10** [comment]
I just ran it with no problem whatsoever:

`> PHY <- querxc(qword = "Phylloscopus", download = FALSE)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 32s
11608 recordings found!`
