### ISSUE TITLE
Possible error found in lspec2pdf

### ISSUE THREAD

**Issue by vmoreg00** [maRce10/warbleR#24]
Hi,
I'm re-running a script in which I use the function `lspec2pdf`. It worked in the past, but now (maybe, after an update), it doesn't.

I've seen that maybe, an error has been introduced in lines 8 and 9 of the function:
`if (!is.null(path))`
`  path <- getwd()`

If I am right, the symbol `!` should be removed. Written with it, the function will overwrite the path with the working directory when `path` parameter is not null (i.e.: when the user introduces it).

**Comment by maRce10** [comment]
thanks for the heads up. I fixed the issue. You can reinstall it now from github:

install.packages("devtools")
devtools::install_github("maRce10/warbleR")


cheers
