### ISSUE TITLE
column names in Vignette 2

### ISSUE THREAD

**Issue by GregShriver** [maRce10/warbleR#25]
Hey:

just so you know the example code in the "Import sound files and select signals" vignette throws an error because the column names generated in the following code are not appropriate for the 'selection_table' function.

**Make your data frame into an object of class selection table**
Downstream warbleR functions require selection tables in order to run correctly. Use the function selection_table to convert your data frame into an object of class selection_table. In future versions of warbleR, all functions will require selection table objects of class selection_table.

sels <- selection_table(X = sels)
str(sels)
class(sels)

thanks!
Greg

**Comment by maRce10** [comment]
Hi Greg

thanks for the heads up. The error was due to a change in the Rraven function imp_raven(). I fixed it so it should work find now. Reinstall it from github if you want to give it a try.

cheers

Marcelo
