### ISSUE TITLE
fftw dependency install problem on Linux Debian stable (10)

### ISSUE THREAD

**Issue by paulauvirage** [maRce10/warbleR#26]
Hello

I perhaps should be asking this question to the fftw package maintainer Ulwe Ligges, but could not find a GitHub page for that package. i am trying to install warbleR and failing to install fftw with the following message: 

/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:6: fftw.so] Error 1
ERROR: compilation failed for package ‘fftw’

Prior to that, the console repeatedly prints `fftw_an_INT_guaranteed_to_be_zero' can not be used when making a shared object; recompile with -fPIC` after each line that is run. 

I have tried ensuring the package FFTW3 is in the path of fftw. I have also successfully installed the R package fftw3 (https://github.com/MangoTheCat/fftw3), but I assume warbleR does depend on that. 

Is there any advice you cna give me, or should i contact the fftw package team?

Many thanks

**Comment by maRce10** [comment]
Hi Paul

there some known issues when installing seewave (a strong warbleR dependency). Take a look at this page for solutions:

http://rug.mnhn.fr/seewave/inst.html

hope this helps!

Marcelo
