### ISSUE TITLE
Error en la doble verificación después de la descarga de archivos MP3

### ISSUE THREAD

**Issue by pau-vazquezc** [maRce10/warbleR#29]
Hola Marcelo te envió el problema al descargar grabaciones que salio durante la clase 
La función es "quer_xc" y me salio este error
" Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: no fue posible abrir la URL 'https://www.xeno-canto.org/download.php?XC=NA' "

Saludos
Pau

**Comment by maRce10** [comment]
Hola Pau 

ya lo arregle. Re-instalalo de nuevo desde github asi:

devtools::install_github("maRce10/warbleR")

saludos!

**Comment by spatialaudiolabs** [comment]
Hi Marcelo

I still have this issue, I have removed the package and reinstalled it from github, same issue, the code I'm running is below. 

```{r load_packages, message=FALSE, eval=FALSE}
# Load the packages
library(warbleR)
library(bioacoustics)
library(tools)
library(randomForest)
library(tensorflow)
library(tuneR)
```
```{r xeno1, message=FALSE, eval=FALSE}
df = quer_xc(qword ='Troglodytes troglodytes type:call cnt:"United Kingdom"', download = FALSE)
df = df[df$Vocalization_type=="call",]
df = df[df$Quality=="A",]
df = df[1:4,]
```
```{r xeno4, eval=FALSE}
# Visualize your data frame
View(df)
# We will work in the R temp directory
wd <- tempdir()
# Create a data directory if it does not exist
data_dir <- file.path(wd, "data")
if(!dir.exists(data_dir))
  dir.create(data_dir)
# Download the MP3 files into your data directory
quer_xc(X = df, download = TRUE, path = data_dir)
```

and then the error

Downloading files...
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=06s  
double-checking downloaded files
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=00s  cannot open URL 'https://www.xeno-canto.org/download.php?XC=NA': HTTP status was '500 Internal Server Error'

Am I doing something wrong somewhere? 

thank you Marcelo!

Axel

**Comment by maRce10** [comment]
HI Axel

It returns an error but after all files have been downloaded. So it is a
bug but doesn't affect the final output. I will fix it in the next few days.


thanks for the heads up


Marcelo

**Comment by maRce10** [comment]
I actually just fixed it. Please install it again.

**Comment by pau-vazquezc** [comment]
Gracias Marcelo, lo instalaré de nuevo, cuídate mucho.
Saludos 😁



Pau
