### ISSUE TITLE
Error in compare.methods function

### ISSUE THREAD

**Issue by akroner1** [maRce10/warbleR#30]
Hello, 
I am trying to work through your example of the `compare.methods` function and have been receiving the following error. `Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'` 
I have tried the examples from your [website](https://marce10.github.io/2017/02/17/Choosing_the_right_method_for_measuring_acoustic_signal_structure.html) and in the R documentation for the functions, as well as trying it with a selection table of my own data. All return the same error.  I assume this error is with the underlying random sample selection, but I do not know how to correct it to run the function.  I will also note that I am using warbleR package version 1.1.22
Thank you

**Comment by maRce10** [comment]
Hi 

thanks for the heads-up. I just fixed this bug. Please re-install warbleR from github:

devtools::install_github("maRce10/warbleR")
