### ISSUE TITLE
Error in file.copy(from = wv, to = file.path(path, "silence-removed_files",  :    more 'from' files than 'to' files

### ISSUE THREAD

**Issue by neon-ninja** [maRce10/warbleR#31]
Hi,

I'm trying to use the rm_sil function, but I'm getting this error:

`Error in file.copy(from = wv, to = file.path(path, "silence-removed_files",  :    more 'from' files than 'to' files`

which I think might be due to there being no silence detected in my input wave files.

**Comment by maRce10** [comment]
Hi,

were you able to figure it out?

Marcelo

**Comment by neon-ninja** [comment]
Hi @maRce10  - no, I'm still having this problem with the latest version on CRAN. Here's a sample wav file that causes this problem:

[alpha.zip](https://github.com/maRce10/warbleR/files/6818992/alpha.zip)

All that is output in the silence-removed_files folder is this image:

![alpha wav rm silence](https://user-images.githubusercontent.com/3378822/125694319-9d66c1f7-2c64-47a5-8f72-3b3ff00b70bf.jpeg)

**Comment by maRce10** [comment]
I just fixed the bug. Please reinstall from gthub and let me know. 

thanks

**Comment by neon-ninja** [comment]
Thanks, your latest commit fixed it for me
