### ISSUE TITLE
quer_ml

### ISSUE THREAD

**Issue by LR234234** [maRce10/warbleR#33]
Hi!
When I try to use quer_ml in warbleR (1.1.24) with R, it tells me: 'could not find function "quer_ml"'
What is wrong? Would be very happy about any help!
Best wishes,
Ralph

**Comment by LR234234** [comment]
Ok, it seems to have been removed with version 1.1.16:
https://cran.r-project.org/web/packages/warbleR/news/news.html

Are there any news, when it will be available again?
Thanks in advance!

**Comment by maRce10** [comment]
Hi

They changed some things in the ML data base that broke the function. Unfortunately I haven't had time to look at it.
