### ISSUE TITLE
Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘Wave’ for signature ‘"Wave"’

### ISSUE THREAD

**Issue by axelspatialaudiolabs** [maRce10/warbleR#36]
Hi Marcelo

I'm trying to run this code but I get this error
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Wave’ for signature ‘"Wave"’

Code below, I tried with multichannel or mono files, of different sizes, still same error.

`
library(warbleR)
library(tuneR)
library(seewave)
memory.limit(size=56000)

audiofile_df_sel_tab_02 <- selection_table(whole.recs = TRUE)

file1 <- read_wave(audiofile_df_sel_tab_02, index = 1, channel = 1)
file2 <- read_wave(audiofile_df_sel_tab_02, index = 1, channel = 1)

audiofile_W <- Wave(file1 + file2 + 3) # summing the amplitude of two objects and adding 3 dB`

But if I run the below code on a single audio file it works fine:

`audiofile_a_format <- readWave("./0404_CAMB-T001.wav", toWaveMC = T)
memory.limit(size=56000)

audiofile_FLU <- audiofile_a_format[,1]
audiofile_FRD <- audiofile_a_format[,2]
audiofile_BLD <- audiofile_a_format[,3]
audiofile_BRU <- audiofile_a_format[,4]

audiofile_W <- Wave(audiofile_FLU + audiofile_FRD + audiofile_BLD + audiofile_BRU + 3)`

I was wondering if read_wave is different in other ways from readWave, not only that it's able to read selection tables.

Thanks

**Comment by maRce10** [comment]
Hi Axel, can you pelase tell me which function gives you that error?

**Comment by axelspatialaudiolabs** [comment]
Hi Marcelo

library(warbleR)
library(tuneR)
library(seewave)
memory.limit(size=56000)

audiofile_df_sel_tab_02 <- selection_table(whole.recs = TRUE)

file1 <- read_wave(audiofile_df_sel_tab_02, index = 1, channel = 1)
file2 <- read_wave(audiofile_df_sel_tab_02, index = 1, channel = 1)

audiofile_W <- Wave(file1 + file2 + 3) # summing the amplitude of two objects and adding 3 dB`

the last line gives me the error. 
It seems like I can't create a Wave file with Wave objects exported from a selection table. I thought the signature is something related to the type of Wave object created.

Axel

**Comment by maRce10** [comment]
Ok I see. The Wave function takes the amplitude vectors, not the wave objects.
Here is an example:

`library(warbleR)
library(NatureSounds)

data("lbh.est")

file1 <- read_wave(lbh.est, index = 1, channel = 1)
file2 <- read_wave(lbh.est, index = 1, channel = 1)

audiofile <- Wave(left = file1@left, right = file1@left, samp.rate = file1@samp.rate, bit = file1@bit)
`
You an also create a multichannel wave object:

`mc_audiofile <- WaveMC(data = list(file1@left, file1@left, file1@left), samp.rate = file1@samp.rate, bit = file1@bit)`

hope this helps!

**Comment by axelspatialaudiolabs** [comment]
Ok thank you, but what I need to do is amplitude summing of three Wave objects, which I can do with Wave objects created with tuneR::readWave, but not with objects created with warbleR::read_wave. Does it makes sense?

**Comment by maRce10** [comment]
OK, for that you can do this:

```
library(warbleR)
library(NatureSounds)

data("lbh.est")

file1 <- read_wave(lbh.est, index = 1, channel = 1)
file2 <- read_wave(lbh.est, index = 1, channel = 1)

audiofile <- Wave(left = file1@left + file2@left, samp.rate = file1@samp.rate, bit = file1@bit)


```

**Comment by axelspatialaudiolabs** [comment]
oh amazing, thank you Marcelo!
