### ISSUE TITLE
could not find function "freq_ts"

### ISSUE THREAD

**Issue by wendyerb** [maRce10/warbleR#38]
Error in freq_ts(ext_st, wl = 512, length.out = 20, wn = "hanning", ovlp = 70,  : 
  could not find function "freq_ts"

A couple of weeks ago "ffts" stopped working and after about an hour of research, I learned that the function had been deprecated to freq_ts (https://rdrr.io/cran/warbleR/src/R/deprec_funs.R). ** Please note that this change was not reported when using the command "print(new_function_names)" so it took a very long time to discover the problem **

Yesterday, I tried to use "freq_ts" and got the above error (which I also got today, even after installing the latest version using "install_gihub").

For some inexplicable reason, "ffts" works again but doesn't seem to track F0 as well as "freq_ts" (i.e., the contour jumps to upper harmonics).

**Comment by maRce10** [comment]
I just ran this code with no problem:

devtools::install_github("maRce10/warbleR")

library(warbleR)

data(list = c("Phae.long1", "Phae.long2","lbh_selec_table"))
writeWave(Phae.long1, file.path(tempdir(), "Phae.long1.wav")) #save sound files 
writeWave(Phae.long2, file.path(tempdir(), "Phae.long2.wav")) #save sound files 

# run function with dominant frequency 
freq_ts(X = lbh_selec_table, length.out = 30, flim = c(1, 12), bp = c(2, 9), 
        wl = 300, pb = FALSE, path = tempdir())

**Comment by wendyerb** [comment]
It started working for me earlier today when I reinstalled WarbleR using install.packages() function and restarted R Studio. The R Documentation file for WarbleR also wasn't working for me yesterday (I was getting an internal server error), so I'm not sure what was happening...but all is well now. Thanks much!

**Comment by maRce10** [comment]
No problem. Thank you for reporting bugs!
