### ISSUE TITLE
Autodetect: Error in readBin(con, int, n = N, size = bytes, signed = (bytes != 1), : invalid 'n' argument

### ISSUE THREAD

**Issue by LittleAlle** [maRce10/warbleR#39]
Hi,
While trying to run an autodetect on some short audio files I got this error messages and have absolutely no idea where it comes from. 

Error in readBin(con, int, n = N, size = bytes, signed = (bytes != 1),  : 
  invalid 'n' `argument

I tried with just one really short audio but I got the same. Any idea what's the issue here ?
Thanks !

**Comment by maRce10** [comment]
Try decreasing window length (wl). how long is audio?
