### ISSUE TITLE
Autodetect doesn't create image files

### ISSUE THREAD

**Issue by luizafp** [maRce10/warbleR#40]
I've being trying to use the autodect function. The detection is working (for most files), but autodect does not create images files.

any help?

autodetec(flist = sub, bp = c(2.5, 8.7), threshold = 10, mindur = 0.3, maxdur = 0.8, envt="abs",
          ssmooth = 300, ls = TRUE, res = 100, 
          flim = c(1, 5), wl = 300, set =TRUE, sxrow = 8, rows = 10, 
          redo = TRUE,img = TRUE, it = "tiff")

**Comment by maRce10** [comment]
autodetec() images have been deprecated. You should be getting a message about it. 

Take a look at this tutorial on how to create spectrograms from the autodetec() output. 

https://ndownloader.figshare.com/files/27242135

Those are a bit more detailed than the previous versions as they show the amplitude envelope along with the spectrogram
