### ISSUE TITLE
freq_range no recursive option?

### ISSUE THREAD

**Issue by swricci** [maRce10/warbleR#42]
I am consulting on an acoustics project where the data files are organized within folders by date. The imp_raven function works presumably because of the recursive = TRUE option. I am having issues with the freq_range function because the wav files are in subdirectories of the provided path. Is there an easy fix for this or can this functionality be added in a future release?

**Comment by maRce10** [comment]
Not really. Take a look at the [consolidate()](https://marce10.github.io/warbleR/reference/consolidate.html) function to put all sound files on a single folder.
