### ISSUE TITLE
resample_est_waves

### ISSUE THREAD

**Issue by jkvrtilek** [maRce10/warbleR#43]
I am trying to resample bat recordings taken at a sampling rate of 500 kHz down to 250 kHz. Below is the code; the warnings; spectrograms of the same detection made before and after resampling; and an extended selection table of that detection.

CODE
# standardize sampling rate
extSelTable <- resample_est_waves(extSelTable, samp.rate = 250, avoid.clip = TRUE)

WARNINGS
sox WARN dither: no `shibata' filter is available for rate 250000; using sloped TPDF
sox WARN dither: dither clipped 27978 samples; decrease volume?

I think the filter warning isn't a problem, but the clipping might be. Would it be possible to add the -G flag inside the sox call to avoid clipping? Or is there something else we can try to avoid restructuring the signal?

SPECTROGRAMS
Pre-resampling:
<img width="400" alt="pre_resampling_zelda31562" src="https://user-images.githubusercontent.com/79934668/140977412-96fb9a58-baf1-4c19-88df-4d4fa52bd749.png">

Post-resampling:
<img width="401" alt="post_resampling_zelda31562" src="https://user-images.githubusercontent.com/79934668/140977455-c0b3f7ce-8c39-46c0-878d-fbc9b8a73505.png">

EST
https://drive.google.com/file/d/1yuGnFz-ennzGHKs7Dm2D6iyDua47WQzU/view?usp=sharing

Thank you!

**Comment by maRce10** [comment]
Hi 

thanks for reporting the issue. I just tried the code and was able to resample without having any issue (the spectrograms before and after look the same). Can you try to install the latest version from github and run it again?

Marcelo

**Comment by jkvrtilek** [comment]
Hi Marcelo,
I was using the latest version of warbleR according to the version number, but not installed from github.
After installing from github, it seems to work fine. Thank you!
Julia
