### ISSUE TITLE
Can't download files from xeno-canto

### ISSUE THREAD

**Issue by mjw246** [maRce10/warbleR#45]
If I write the following code:

CGDO.rec <- query_xc(qword='nr:408879',download = FALSE)
nrow(CGDO.rec)
str(CGDO.rec)

R successfully locates the recording I want to download from xeno-canto. However when i try to download the recording to my directory:
query_xc(X=CGDO.rec); or I change the FALSE to TRUE in the previous code

I get a series of error messages (see attached document). I have restarted R and installed devtools along with all the other packages. Any idea why this is happening?

![Screen Shot 2022-02-08 at 3 57 18 PM](https://user-images.githubusercontent.com/10456720/153074948-4553efc6-d83f-4a54-ae37-80a94e378ffe.jpg)
?

**Comment by maRce10** [comment]
same issue than #44. It was already fixed. Please install again from github: 

`devtools::install_github("maRce10/warbleR")`

**Comment by mjw246** [comment]
Thank you! Yes I just figured that out, much appreciated!
________________________________
