### ISSUE TITLE
Error message WarbleR

### ISSUE THREAD

**Issue by SofiaMedellin** [maRce10/warbleR#46]
Hello,

I've been using WarbleR to download files from Xeno-canto and then convert them from mp3 to wav. Yesterday I had a message saying "R session Aborted. R encountered a fatal error. The session was terminated" after I ran the function "mp32wav", so I restarted my laptop, then I detached the package, installed it again like this:

_detach(package:warbleR, unload=TRUE)
install.packages("devtools")
devtools::install_github("maRce10/warbleR")
1
Yes
library(warbleR)_

and it worked for a while. However, today I had exactly the same problem. I downloaded the files, then, when I was trying to convert them, it gave me the "R session aborted" so I continued to do exactly the same but this time it did not work.
Then, it gave me this error:

_configure: error: Could not find cmake
ERROR: configuration failed for package ‘bioacoustics’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/bioacoustics’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/bioacoustics’

The downloaded source packages are in
	‘/private/var/folders/wx/w6wgx2kx5j9dkh2191wtcm680000gn/T/RtmpaRIwUG/downloaded_packages’_
	

And now, when I try to even load the package using library(warbleR), I get this error:

_Error: package or namespace load failed for ‘warbleR’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/warbleR/R/warbleR.rdb' is corrupt
In addition: Warning message:
In get(method, envir = home) : internal error -3 in R_decompress1_

Is there anything else I can do?
Thank you for reading,

Sofía

**Comment by maRce10** [comment]
Hi Sofia,

it seems that you need to install cmake first for bioacoustics to work: 

https://cmake.org/install/

This might also help:

https://github.com/rstudio/shinyapps-package-dependencies/issues/203



Marcelo

**Comment by SofiaMedellin** [comment]
Hello again,

thank you for your help in the end it worked. However, I've been struggling for a while with the "mp32wav" function: every time I need to convert more than 40 or 60 files (it's not always the same amount of files when it happens), it works until a certain percentage and then before it finishes, it immediately gives me "fatal error, R session aborted". Do you know what can I do to fix this?

Thank you again,

Sofía

**Comment by SofiaMedellin** [comment]
<img width="1420" alt="Captura de Pantalla 2022-03-07 a la(s) 1 35 58 p  m" src="https://user-images.githubusercontent.com/99329859/157035742-1e073c1f-07db-47b0-a095-07be4c047078.png">


As you can see, It loaded until 36% and then it fail

**Comment by maRce10** [comment]
That's weird. Looks like a memory issue. Are you using parallel computing (parallel > 1)? Do you have a extremely long recording? If so try excluding it to see how that goes.
