### ISSUE TITLE
query_xc issue

### ISSUE THREAD

**Issue by jonathanpdrury** [maRce10/warbleR#47]
Hello,

I keep getting the following error when running query_xc:

CR.recs <- querxc(qword = 'cnt:"costa rica"', download = FALSE)
Error in file(con, "r") : 
  cannot open the connection to 'https://www.xeno-canto.org/api/2/recordings?query=cnt:"costa%20rica"'
In addition: Warning message:
In file(con, "r") :
  URL 'https://www.xeno-canto.org/api/2/recordings?query=cnt:"costa%20rica"': status was 'Peer certificate cannot be authenticated with given CA certificates'

Yet when I copy and paste the URL for the api link, the page appears to display everything just fine. I've updated R and reinstalled warbleR from the github and still get the message. Thanks very much for your help and your work on this package!

**Comment by maRce10** [comment]
same issue than[ #44](https://github.com/maRce10/warbleR/issues/44). It was already fixed. Please install again from github: 

`devtools::install_github("maRce10/warbleR")`
