### ISSUE TITLE
File naming with X argument

### ISSUE THREAD

**Issue by thk686** [maRce10/warbleR#48]
It seems that when you use `warbleR::query_xc(X = df, download = TRUE, file.name = NULL)`, the saved files do not have the correct names. Each file in my application is named as a list of geographical coordinates followed by the recording id. It should just be the recording id. All of my attempts at using `file.name` fail to change these names.

**Comment by maRce10** [comment]
Hi, could you share a minimal reproducible example? Like the first 2 rows of the data frame "df"? This seems to work fine:

`q1 <- query_xc(qword = "Hyliota violacea", path = tempdir(), download = FALSE)`

`query_xc(X = q1, path = tempdir(), file.name = NULL)`

`list.files(tempdir(), pattern = "mp3$")`

**Comment by thk686** [comment]
I think I figured it out -- I was passing an 'sf' (spatial) data frame,
which is augmented with a geometry column. WarbleR was adding the spatial
coordinates to the file names. I don't have time to demo it but I assume
converting to an ordinary data frame by dropping the geometry column will
fix the problem.
