### ISSUE TITLE
The variation “dest.path” of  function "mp3_2_wav" doesn't work

### ISSUE THREAD

**Issue by Yaniel-Wong** [maRce10/warbleR#53]
Hi, I'm trying to convert  mp3 to wav with warbleR on Linux, the wav files doesn't exist in my target folder but the mp3 folder.  The path has been sent to "dest.path" and no warning or error messages, it seems no use on my R session.

Here's part of my code, diclist is the list of a series of my folders:
```
name <- diclist[i,1]
  mp3path <- paste0("~/R/song_download/data/songdata/",name)
  wavpath <- paste0("~/R/song_download/data/xeno_wav/",name)
  if (file.exists(wavpath)==F){
    dir.create(wavpath) 
  }
  mp3_2_wav(samp.rate = 44.1,path = mp3path,dest.path = wavpath,
            overwrite = T,parallel = 4)
```
Any advice on how to resolve this problem would be much appreciated!

**Comment by maRce10** [comment]
Hi,

I just try the 'dest.path' argument and it works:

 
```
# download mp3 files from xeno-canto
  query_xc(qword = "Phaethornis aethopygus", download = TRUE, path = tempdir())
  
# create new folder
  new.path <- file.path(tempdir(), "wavs")
  dir.create(new.path) 

# Convert  files to .wav format
  mp3_2_wav( samp.rate = 48, dest.path = new.path)

# check files in new folder
list.files(path = new.path)

```
So not sure what is going on with your code. Sometimes you don't get error messages when using parallel. Try running parallel = 1.

**Comment by andrew-1234** [comment]
Hi, 
I'm getting the same issue. 
Running this code:
```
# download mp3 files from xeno-canto
  query_xc(qword = "Phaethornis aethopygus", download = TRUE, path = tempdir())
  
# create new folder
  new.path <- file.path(tempdir(), "wavs")
  dir.create(new.path) 

# Convert  files to .wav format
  mp3_2_wav(path = tempdir(), dest.path = new.path)

# check files in new folder
list.files(path = tempdir())
list.files(path = new.path)
```

list.files new path returns `character(0)`
list.files tempdir shows both .mp3 and .wav files in the tempdir.

I replicated this in my own project; with dest.path specified the .wavs remain with the .mp3s, with parallel = 1 . 
Here is my version info.
```
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things      
```
Thanks!

**Comment by maRce10** [comment]
Thanks, but I do get the wav files in new.path. What warbleR version are you using? Try installing the latest version from github

**Comment by andrew-1234** [comment]
This was with 1.1.27. I just updated to latest version and now the function does not work at all for me. I get the error:

```
sh: sox: command not found
Error in system(cll, ignore.stdout = FALSE, intern = TRUE) : 
  error in running command
```

Is sox required for a default settings `mp3_2_wav`? I don't have it installed. And tuneR is `1.4.1`
I'll keep checking and try to see what could be the issue. 

Thanks

**Comment by maRce10** [comment]
yes you need sox to be installed. Would be cool to add a double-checking step to make sure it is installed, but not sure how to make work on different OS.

**Comment by andrew-1234** [comment]
Thanks, I installed sox and the function works
