### ISSUE TITLE
Error: package 'warbleR' 1.1.27 was found, but >= 1.1.28 is required by 'ohun'

### ISSUE THREAD

**Issue by choudavid0** [maRce10/warbleR#55]
Hi, 
I am trying to install package ohun but the error occurs as below:
Error: package 'warbleR' 1.1.27 was found, but >= 1.1.28 is required by 'ohun'
Execution halted
ERROR: lazy loading failed for package 'ohun'

Although the warbleR package on github displays the version is 1.1.28, I can only download version 1.1.27
Before the error the code was running like this:

Running `R CMD build`...
* checking for file 'C:\Users\User\AppData\Local\Temp\RtmpOO7XTW\remotes48c11866478\maRce10-ohun-742a5bd/DESCRIPTION' ... OK
* preparing 'ohun':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'ohun_0.1.0.tar.gz'
* installing *source* package 'ohun' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading

Hope this problem can be fixed.
Best regards, 
David

**Comment by maRce10** [comment]
is this an ohun issue?

**Comment by choudavid0** [comment]
Yes

**Comment by maRce10** [comment]
no worries. I think you can fix it by installing warbleR from github first:
```
remotes::install_github("maRce10/warbleR")
```
