### ISSUE TITLE
The question about measurement of function gaps()

### ISSUE THREAD

**Issue by auman-chan** [maRce10/warbleR#58]
Hi Marcelo
I used function gaps() but I had some puzzle. My definition of "gaps" is the time between end of selection and the start of the next selection (the red arrow in the picture below).
![屏幕截图 2023-03-13 111443](https://user-images.githubusercontent.com/89596802/224600445-ca50ed87-002f-46a7-8ab8-576a0a17bc88.png)

but when I run gaps() with the example data, the result like this (reorder by sound.file and start):

![image](https://user-images.githubusercontent.com/89596802/224602725-6496f104-18f6-4539-bb85-b74c83d2c91a.png)

It seems the function measures the time between "start" of first selection and "end" of second selection, not the "gap" I think.
Do I have any misunderstanding of the "gap"? 

Thanks

**Comment by maRce10** [comment]
Hi 

Thanks for reporting. I fixed the issue so it should work find now.

cheers
