### ISSUE TITLE
duration_wavs

### ISSUE THREAD

**Issue by frebur** [maRce10/warbleR#77]
Error en duration_wavs(sub): 
  no se pudo encontrar la función "duration_wavs"
la funcion tampoco figura en
 ls("package:warbleR") o cambio de nombre?

**Comment by maRce10** [comment]
implement ss FM method from: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12223

**Comment by maRce10** [comment]
sip ahora es: [duration_sound_files()](https://marce10.github.io/warbleR/reference/duration_sound_files.html)
